Updating key pairs in data parser
cidgoh/COVID-MVP pull request #145
Opened 2022-12-06 07:05 UTC by anwarMZ

Few updates to reflect changes in gvf files for visualization:

- Updated attribute `status` to distinguish between _actively_circulating_ and _de-escalated_ variants. `status` was previously used to distinguish between VOCs, VOIs and VUM.
- changed the attribute `who_variant` to `variant`  because WHO is not updating variant list as often and we need to keep up with different sources so removing WHO tag
- `variant_type` is now replacing `status` to distinguish VOCs, VOIs ad VUMs

2022-12-06 21:36 UTC, ivansg44 requested changes
I think you should add the new gvf files and surveillance reports to `reference_data_/` and `reference_surveillance_reports/`, and I should implement a visual encoding for de-escalating and circulating strains, before we merge this PR.

2022-12-06 23:34 UTC, anwarMZ commented on data_parser.py
> +            circulating_strains,
Yes, we will differentiate these in the visualization too.

2023-01-09 21:34 UTC, ivansg44 commented on data_parser.py
> +            circulating_strains,
Resolved with 099e341

2023-01-09 21:37 UTC, ivansg44 approved these changes
I'm going to merge this

2023-01-09 21:37 UTC, merged